services:
  - type: web
    name: vretail
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vretail.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vretail-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
